services:
  wg-easy:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run serve
    volumes:
      - ./src/:/app/
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      LANG: ru
      WG_HOST: 192.168.23.177
      PASSWORD_HASH: $$2a$$12$$PdvZzLGdcKTdIaNKVKGGAud4jnytKBOypg/wNI7LKzwTzdWQxjl7u
      MONGO_URI: mongodb://mongo:27017/wgeasy
      WEBUI_HOST: 0.0.0.0

    networks:
      - wg-easy-network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - wg-easy-network

volumes:
  mongodb_data:

networks:
  wg-easy-network:
    driver: bridge