services:
  wg-easy:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm start
    volumes:
       - ./src:/app/src
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      LANG: ru
      WG_HOST: 192.168.23.177
      PASSWORD_HASH: $$2a$$12$$PdvZzLGdcKTdIaNKVKGGAud4jnytKBOypg/wNI7LKzwTzdWQxjl7u
      MONGO_URI: mongodb://mongo:27017/wgeasy
      WEBUI_HOST: 0.0.0.0
    networks:
      - wg-easy-network
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:51821/api/session"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - wg-easy-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh 127.0.0.1:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  mongodb_data:

networks:
  wg-easy-network:
    driver: bridge